name: ::SNAP::
version: "::VERSION::"
summary: ::SUMMARY::
description: |
::DESCRIPTION::
confinement: strict
grade: stable
icon: ../deb/opt/::FILE::/Icon/256x256/::FILE::.png

apps:
  ::SNAP:::
    command: bash $SNAP/::FILE::.sh
    desktop: ::SNAP::.desktop
    plugs: [opengl, x11, network, home, pulseaudio]

parts:
  ::SNAP:::
    plugin: dump
    source: ../deb/opt/::FILE::
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
      - libsdl2-mixer-2.0-0
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - libgles2-mesa