name: ::SNAP::
version: "::VERSION::"
summary: ::SUMMARY::
description: ::DESCRIPTION::
confinement: strict
grade: stable

apps:
  ::FILE:::
    command: ::FILE::.sh
    plugs: [unity7, opengl, x11, network, home]

parts:
  pintown:
    plugin: dump
    source: ../bin
